integration:
  intric:
    base-url: http://base-url.com
    oauth2:
      username: override
      password: override
      token-url: http://token-url.com
    read-timeout-in-seconds: 15
    connect-timeout-in-seconds: 5
  templating:
    base-url: http://base-url.com
    oauth2:
      authorization-grant-type: client_credentials
      client-id: client_id
      client-secret: client_secret
      token-url: http://token-url.com
    read-timeout-in-seconds: 15
    connect-timeout-in-seconds: 5
spring:
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:mariadb:10.6.14:///
  flyway:
    enabled: true
