spring:
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:mariadb:10.6.14:///
  flyway:
    enabled: true

stale-session-reaper:
  enabled: false

scheduler:
  stale-session-reaper:
    name: stale-session-reaper
    cron:
      expression: '-' # Expression set in the config server or defaulted to '-'
    shedlock-lock-at-most-for: PT2M # Defaulted to 2 minutes
    maximum-execution-time: PT2M # Defaulted to 2 minutes

integration:
  eneo:
    base-url: http://base-url.com
    oauth2:
      token-url: http://token-url.com
      client-id: override
      client-secret: override
      authorization-grant-type: client_credentials
    read-timeout-in-seconds: 15
    connect-timeout-in-seconds: 5
    municipalities:
      2281:
        url: https://api-i-test.sundsvall.se/eneo-sundsvall/1.0
        api-key: aKey
      1984:
        url: https://api-i-test.stromstad.se/eneo-arboga/1.0
        api-key: anotherKey
  templating:
    base-url: http://base-url.com
    oauth2:
      authorization-grant-type: client_credentials
      client-id: client_id
      client-secret: client_secret
      token-url: http://token-url.com
    read-timeout-in-seconds: 15
    connect-timeout-in-seconds: 5
